var car = 'subaru';
console.log("Is car == 'subaru'? I predict True.");
console.log(car == 'subaru');
console.log("________________________________________________________________");
console.log("Is car == 'honda'? I predict False.");
console.log(car == 'honda');
console.log("________________________________________________________________");
console.log("Is car != 'toyota'? I predict True.");
console.log(car != 'toyota');
console.log("________________________________________________________________");
console.log("Is car != 'subaru'? I predict False.");
console.log(car != 'subaru');
console.log("________________________________________________________________");
console.log("Is car === 'subaru'? I predict True.");
console.log(car === 'subaru');
console.log("________________________________________________________________");
console.log("Is car === 'Subaru'? I predict False.");
console.log(car === 'Subaru');
console.log("________________________________________________________________");
console.log("Is car !== 'honda'? I predict True.");
console.log(car !== 'honda');
console.log("________________________________________________________________");
console.log("Is car !== 'subaru'? I predict False.");
console.log(car !== 'subaru');
console.log("________________________________________________________________");
console.log("Is car.startsWith('sub')? I predict True.");
console.log(car.startsWith('sub'));
console.log("________________________________________________________________");
console.log("Is car.endsWith('ru')? I predict True.");
console.log(car.endsWith('ru'));
console.log("________________________________________________________________");
