var mountains = ['Mount Everest', 'K2', 'Kangchenjunga', 'Matterhorn', 'Mount Kilimanjaro'];
var rivers = ['Nile', 'Amazon', 'Yangtze', 'Mississippi', 'Danube'];
var countries = ['Afghanistan', 'Pakistan', 'Turkey', 'Iraq', 'Palestine'];
var cities = ['Karachi', 'Istanbul', 'Ghaza', 'Kabul', 'Islamabad'];
var languages = ['Urdu', 'English', 'Spanish', 'Hindi', 'Arabic'];
console.log("\nList of Mountains:");
console.log(mountains);
console.log("\nList of Rivers:");
console.log(rivers);
console.log("\nList of Countries:");
console.log(countries);
console.log("\nList of Cities:");
console.log(cities);
console.log("\nList of Languages:");
console.log(languages);
